name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build build-essential

      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build TurboKV
        run: cmake --build build

      - name: Run Unit Tests
        run: ctest --test-dir build --output-on-failure
